source 'https://api.berkshelf.com'

cookbook 'apt'
cookbook 'ark'
cookbook 'chef-solo-search'
cookbook 'build-essential'
cookbook 'git'
cookbook 'nfs'
cookbook 'sudo'
cookbook 'timezone'
cookbook 'users'
